# Generated by Django 5.0.4 on 2024-04-27 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_purchase_estate'),
        ('landing', '0002_remove_image_estate_apartment_image_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landing.apartment'),
            preserve_default=False,
        ),
    ]
