# Generated by Django 5.0.4 on 2024-04-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_remove_image_estate_apartment_image_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
